const mysql = require('mysql2/promise');
const fs = require('fs');

const cfg = {
  host: process.env.MARIADB_HOST || '127.0.0.1',
  port: parseInt(process.env.MARIADB_PORT || '3307', 10),
  user: process.env.MARIADB_USER || 'rb_user',
  password: process.env.MARIADB_PASSWORD || 'rb_user_secret',
  database: process.env.MARIADB_DATABASE || 'raueberbude',
};

(async function(){
  const outFile = 'raueberbude_backup_before_ha_node.sql';
  const conn = await mysql.createConnection(cfg);
  const [tables] = await conn.query("SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = ?", [cfg.database]);
  const stream = fs.createWriteStream(outFile, { flags: 'w' });
  stream.write(`-- Dump of database ${cfg.database}\n-- Generated by node_db_dump.js\n\nSET FOREIGN_KEY_CHECKS=0;\n\n`);

  for (const row of tables) {
    const table = row.TABLE_NAME;
    stream.write(`-- Table: ${table}\n`);
    const [createRes] = await conn.query(`SHOW CREATE TABLE \`${table}\``);
    stream.write(createRes[0]['Create Table'] + ";\n\n");

    const [rows] = await conn.query(`SELECT * FROM \`${table}\``);
    if (rows.length === 0) {
      stream.write(`-- ${table} is empty\n\n`);
      continue;
    }

    const cols = Object.keys(rows[0]).map(c => `\\\`${c}\\\``).join(', ');
    stream.write(`LOCK TABLES \`${table}\` WRITE;\n`);

    for (let i = 0; i < rows.length; i += 200) {
      const batch = rows.slice(i, i+200);
      const values = batch.map(r => {
        const vals = Object.values(r).map(v => mysql.escape(v));
        return `(${vals.join(', ')})`;
      }).join(',\n');
      stream.write(`INSERT INTO \`${table}\` (${Object.keys(rows[0]).map(c=>`\`${c}\``).join(', ')}) VALUES\n${values};\n`);
    }

    stream.write(`UNLOCK TABLES;\n\n`);
  }

  stream.write('\nSET FOREIGN_KEY_CHECKS=1;\n');
  stream.end();
  await conn.end();
  console.log('Dump written to', outFile);
})();

