FROM node:20-alpine
RUN apk add --no-cache git
WORKDIR /app
COPY package*.json ./
RUN npm install
EXPOSE 4200
CMD ["npx", "ng", "serve", "--host=0.0.0.0", "--port=4200", "--proxy-config=proxy.conf.docker.json", "--poll=2000"]
