import { MigrationInterface, QueryRunner } from "typeorm";

export class AddManyToManyTables1764886566775 implements MigrationInterface {
    name = 'AddManyToManyTables1764886566775'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DROP INDEX \`ux_transcripts_mongo_id\` ON \`transcripts\``);
        await queryRunner.query(`DROP INDEX \`ux_mongo_id\` ON \`categories\``);
        await queryRunner.query(`CREATE TABLE \`llm_instances\` (\`id\` uuid NOT NULL, \`name\` varchar(255) NOT NULL, \`url\` varchar(500) NOT NULL, \`model\` varchar(255) NOT NULL, \`enabled\` tinyint NOT NULL DEFAULT 1, \`isActive\` tinyint NOT NULL DEFAULT 0, \`system_prompt\` text NULL, \`health\` enum ('healthy', 'unhealthy', 'unknown') NOT NULL DEFAULT 'unknown', \`last_health_check\` datetime NULL, \`config\` json NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), INDEX \`IDX_ec2857bc1e1718797135dc71d7\` (\`isActive\`), INDEX \`IDX_ec2857bc1e1718797135dc71d7\` (\`isActive\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`ALTER TABLE \`transcripts\` DROP COLUMN \`mongo_id\``);
        await queryRunner.query(`ALTER TABLE \`categories\` DROP COLUMN \`mongo_id\``);
        await queryRunner.query(`ALTER TABLE \`categories\` DROP COLUMN \`data\``);
        await queryRunner.query(`ALTER TABLE \`app_users\` ADD \`id\` uuid NOT NULL PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`categories\` ADD \`key\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`categories\` ADD UNIQUE INDEX \`IDX_da6f1e4e0c4683302df95d3ae9\` (\`key\`)`);
        await queryRunner.query(`ALTER TABLE \`categories\` ADD \`label\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`app_users\` ADD UNIQUE INDEX \`IDX_5d67cc2e38c80255e768c2b76a\` (\`username\`)`);
        await queryRunner.query(`ALTER TABLE \`app_users\` ADD UNIQUE INDEX \`IDX_14241fb016a330600a7e0efae9\` (\`email\`)`);
        await queryRunner.query(`ALTER TABLE \`app_terminals\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`app_terminals\` DROP COLUMN \`id\``);
        await queryRunner.query(`ALTER TABLE \`app_terminals\` ADD \`id\` uuid NOT NULL PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`app_terminals\` ADD UNIQUE INDEX \`IDX_d3791ca91cbaf198fc6a072f7f\` (\`terminal_id\`)`);
        await queryRunner.query(`ALTER TABLE \`app_terminals\` CHANGE \`type\` \`type\` enum ('browser', 'mobile', 'tablet', 'kiosk', 'smart-tv', 'other') NOT NULL DEFAULT 'browser'`);
        await queryRunner.query(`ALTER TABLE \`app_terminals\` DROP COLUMN \`assigned_user_id\``);
        await queryRunner.query(`ALTER TABLE \`app_terminals\` ADD \`assigned_user_id\` uuid NULL`);
        await queryRunner.query(`ALTER TABLE \`app_terminals\` DROP COLUMN \`allowed_actions\``);
        await queryRunner.query(`ALTER TABLE \`app_terminals\` ADD \`allowed_actions\` json NOT NULL DEFAULT '[]'`);
        await queryRunner.query(`ALTER TABLE \`transcripts\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`transcripts\` DROP COLUMN \`id\``);
        await queryRunner.query(`ALTER TABLE \`transcripts\` ADD \`id\` uuid NOT NULL PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`transcripts\` DROP COLUMN \`terminal_id\``);
        await queryRunner.query(`ALTER TABLE \`transcripts\` ADD \`terminal_id\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`transcripts\` CHANGE \`confidence\` \`confidence\` decimal(3,2) NULL`);
        await queryRunner.query(`ALTER TABLE \`intent_logs\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`intent_logs\` DROP COLUMN \`id\``);
        await queryRunner.query(`ALTER TABLE \`intent_logs\` ADD \`id\` uuid NOT NULL PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`intent_logs\` DROP COLUMN \`timestamp\``);
        await queryRunner.query(`ALTER TABLE \`intent_logs\` ADD \`timestamp\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`intent_logs\` CHANGE \`confidence\` \`confidence\` decimal(3,2) NULL`);
        await queryRunner.query(`ALTER TABLE \`intent_logs\` DROP COLUMN \`terminal_id\``);
        await queryRunner.query(`ALTER TABLE \`intent_logs\` ADD \`terminal_id\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`ha_entities\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`ha_entities\` DROP COLUMN \`id\``);
        await queryRunner.query(`ALTER TABLE \`ha_entities\` ADD \`id\` uuid NOT NULL PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`ha_entities\` ADD UNIQUE INDEX \`IDX_1ea0706eb5defaadb39b56895d\` (\`entity_id\`)`);
        await queryRunner.query(`ALTER TABLE \`ha_entities\` CHANGE \`domain\` \`domain\` varchar(100) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`categories\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`categories\` DROP COLUMN \`id\``);
        await queryRunner.query(`ALTER TABLE \`categories\` ADD \`id\` uuid NOT NULL PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`categories\` CHANGE \`created_at\` \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`categories\` CHANGE \`updated_at\` \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`CREATE INDEX \`IDX_ecf206db163e4bc08e88bfcdda\` ON \`transcripts\` (\`user_id\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_673515f09ae603ef71915047ce\` ON \`transcripts\` (\`terminal_id\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_fb031d43374737ae7b7a1e581e\` ON \`transcripts\` (\`category\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_223c1418c7ac4b50812c0d7265\` ON \`transcripts\` (\`model\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_21ec8470934fc237ea19fba9a6\` ON \`transcripts\` (\`assigned_area_id\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_7d01cbfd14c5e685e5c6516a44\` ON \`transcripts\` (\`assigned_entity_id\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_41d12af0dce374054df3541fc0\` ON \`transcripts\` (\`created_at\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_b10b86503aba4f48203e132f51\` ON \`transcripts\` (\`is_valid\`, \`created_at\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_d64eeaeb12f271e201a9d96cb0\` ON \`transcripts\` (\`category\`, \`created_at\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_9544ecdb63459e40f88dc0755f\` ON \`transcripts\` (\`model\`, \`created_at\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_1e24a2da9176be9aa08a268287\` ON \`transcripts\` (\`terminal_id\`, \`created_at\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_b9f52ed4eabe7906d828370a14\` ON \`transcripts\` (\`user_id\`, \`created_at\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_12a5a6ea467f7c303bf0bf069b\` ON \`intent_logs\` (\`timestamp\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_adba5baca6d1fe824595fcec9b\` ON \`intent_logs\` (\`intent\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_3ddab4f8d5e466872aee62072e\` ON \`intent_logs\` (\`terminal_id\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_67ee9eb7ce93cf77f2163d6bf9\` ON \`intent_logs\` (\`created_at\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_ed4631abce9c0c8d398800f4a4\` ON \`intent_logs\` (\`terminal_id\`, \`created_at\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_e01da6bdf7cda00df1a15b2b16\` ON \`intent_logs\` (\`intent\`, \`created_at\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_67ee9eb7ce93cf77f2163d6bf9\` ON \`intent_logs\` (\`created_at\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_3ddab4f8d5e466872aee62072e\` ON \`intent_logs\` (\`terminal_id\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_adba5baca6d1fe824595fcec9b\` ON \`intent_logs\` (\`intent\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_12a5a6ea467f7c303bf0bf069b\` ON \`intent_logs\` (\`timestamp\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_827669cde0687fadfa4153b9c9\` ON \`ha_entities\` (\`area\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_a51fbf003e7c746fc792653da7\` ON \`ha_entities\` (\`domain\`)`);
        await queryRunner.query(`ALTER TABLE \`app_terminals\` ADD CONSTRAINT \`FK_d041169ca324e0f8a928f0840e4\` FOREIGN KEY (\`assigned_user_id\`) REFERENCES \`app_users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`app_terminals\` DROP FOREIGN KEY \`FK_d041169ca324e0f8a928f0840e4\``);
        await queryRunner.query(`DROP INDEX \`IDX_a51fbf003e7c746fc792653da7\` ON \`ha_entities\``);
        await queryRunner.query(`DROP INDEX \`IDX_827669cde0687fadfa4153b9c9\` ON \`ha_entities\``);
        await queryRunner.query(`DROP INDEX \`IDX_12a5a6ea467f7c303bf0bf069b\` ON \`intent_logs\``);
        await queryRunner.query(`DROP INDEX \`IDX_adba5baca6d1fe824595fcec9b\` ON \`intent_logs\``);
        await queryRunner.query(`DROP INDEX \`IDX_3ddab4f8d5e466872aee62072e\` ON \`intent_logs\``);
        await queryRunner.query(`DROP INDEX \`IDX_67ee9eb7ce93cf77f2163d6bf9\` ON \`intent_logs\``);
        await queryRunner.query(`DROP INDEX \`IDX_e01da6bdf7cda00df1a15b2b16\` ON \`intent_logs\``);
        await queryRunner.query(`DROP INDEX \`IDX_ed4631abce9c0c8d398800f4a4\` ON \`intent_logs\``);
        await queryRunner.query(`DROP INDEX \`IDX_67ee9eb7ce93cf77f2163d6bf9\` ON \`intent_logs\``);
        await queryRunner.query(`DROP INDEX \`IDX_3ddab4f8d5e466872aee62072e\` ON \`intent_logs\``);
        await queryRunner.query(`DROP INDEX \`IDX_adba5baca6d1fe824595fcec9b\` ON \`intent_logs\``);
        await queryRunner.query(`DROP INDEX \`IDX_12a5a6ea467f7c303bf0bf069b\` ON \`intent_logs\``);
        await queryRunner.query(`DROP INDEX \`IDX_b9f52ed4eabe7906d828370a14\` ON \`transcripts\``);
        await queryRunner.query(`DROP INDEX \`IDX_1e24a2da9176be9aa08a268287\` ON \`transcripts\``);
        await queryRunner.query(`DROP INDEX \`IDX_9544ecdb63459e40f88dc0755f\` ON \`transcripts\``);
        await queryRunner.query(`DROP INDEX \`IDX_d64eeaeb12f271e201a9d96cb0\` ON \`transcripts\``);
        await queryRunner.query(`DROP INDEX \`IDX_b10b86503aba4f48203e132f51\` ON \`transcripts\``);
        await queryRunner.query(`DROP INDEX \`IDX_41d12af0dce374054df3541fc0\` ON \`transcripts\``);
        await queryRunner.query(`DROP INDEX \`IDX_7d01cbfd14c5e685e5c6516a44\` ON \`transcripts\``);
        await queryRunner.query(`DROP INDEX \`IDX_21ec8470934fc237ea19fba9a6\` ON \`transcripts\``);
        await queryRunner.query(`DROP INDEX \`IDX_223c1418c7ac4b50812c0d7265\` ON \`transcripts\``);
        await queryRunner.query(`DROP INDEX \`IDX_fb031d43374737ae7b7a1e581e\` ON \`transcripts\``);
        await queryRunner.query(`DROP INDEX \`IDX_673515f09ae603ef71915047ce\` ON \`transcripts\``);
        await queryRunner.query(`DROP INDEX \`IDX_ecf206db163e4bc08e88bfcdda\` ON \`transcripts\``);
        await queryRunner.query(`ALTER TABLE \`categories\` CHANGE \`updated_at\` \`updated_at\` datetime(0) NULL`);
        await queryRunner.query(`ALTER TABLE \`categories\` CHANGE \`created_at\` \`created_at\` datetime(0) NULL`);
        await queryRunner.query(`ALTER TABLE \`categories\` DROP COLUMN \`id\``);
        await queryRunner.query(`ALTER TABLE \`categories\` ADD \`id\` char(36) COLLATE "utf8mb4_general_ci" NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`categories\` ADD PRIMARY KEY (\`id\`)`);
        await queryRunner.query(`ALTER TABLE \`ha_entities\` CHANGE \`domain\` \`domain\` varchar(100) NULL`);
        await queryRunner.query(`ALTER TABLE \`ha_entities\` DROP INDEX \`IDX_1ea0706eb5defaadb39b56895d\``);
        await queryRunner.query(`ALTER TABLE \`ha_entities\` DROP COLUMN \`id\``);
        await queryRunner.query(`ALTER TABLE \`ha_entities\` ADD \`id\` varchar(36) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`ha_entities\` ADD PRIMARY KEY (\`id\`)`);
        await queryRunner.query(`ALTER TABLE \`intent_logs\` DROP COLUMN \`terminal_id\``);
        await queryRunner.query(`ALTER TABLE \`intent_logs\` ADD \`terminal_id\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`intent_logs\` CHANGE \`confidence\` \`confidence\` decimal(5,2) NULL`);
        await queryRunner.query(`ALTER TABLE \`intent_logs\` DROP COLUMN \`timestamp\``);
        await queryRunner.query(`ALTER TABLE \`intent_logs\` ADD \`timestamp\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`intent_logs\` DROP COLUMN \`id\``);
        await queryRunner.query(`ALTER TABLE \`intent_logs\` ADD \`id\` varchar(36) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`intent_logs\` ADD PRIMARY KEY (\`id\`)`);
        await queryRunner.query(`ALTER TABLE \`transcripts\` CHANGE \`confidence\` \`confidence\` decimal(5,2) NULL`);
        await queryRunner.query(`ALTER TABLE \`transcripts\` DROP COLUMN \`terminal_id\``);
        await queryRunner.query(`ALTER TABLE \`transcripts\` ADD \`terminal_id\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`transcripts\` DROP COLUMN \`id\``);
        await queryRunner.query(`ALTER TABLE \`transcripts\` ADD \`id\` varchar(36) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`transcripts\` ADD PRIMARY KEY (\`id\`)`);
        await queryRunner.query(`ALTER TABLE \`app_terminals\` DROP COLUMN \`allowed_actions\``);
        await queryRunner.query(`ALTER TABLE \`app_terminals\` ADD \`allowed_actions\` longtext COLLATE "utf8mb4_bin" NULL`);
        await queryRunner.query(`ALTER TABLE \`app_terminals\` DROP COLUMN \`assigned_user_id\``);
        await queryRunner.query(`ALTER TABLE \`app_terminals\` ADD \`assigned_user_id\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`app_terminals\` CHANGE \`type\` \`type\` enum ('desktop', 'mobile', 'voice', 'dashboard') NOT NULL DEFAULT 'desktop'`);
        await queryRunner.query(`ALTER TABLE \`app_terminals\` DROP INDEX \`IDX_d3791ca91cbaf198fc6a072f7f\``);
        await queryRunner.query(`ALTER TABLE \`app_terminals\` DROP COLUMN \`id\``);
        await queryRunner.query(`ALTER TABLE \`app_terminals\` ADD \`id\` varchar(36) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`app_terminals\` ADD PRIMARY KEY (\`id\`)`);
        await queryRunner.query(`ALTER TABLE \`app_users\` DROP INDEX \`IDX_14241fb016a330600a7e0efae9\``);
        await queryRunner.query(`ALTER TABLE \`app_users\` DROP INDEX \`IDX_5d67cc2e38c80255e768c2b76a\``);
        await queryRunner.query(`ALTER TABLE \`categories\` DROP COLUMN \`label\``);
        await queryRunner.query(`ALTER TABLE \`categories\` DROP INDEX \`IDX_da6f1e4e0c4683302df95d3ae9\``);
        await queryRunner.query(`ALTER TABLE \`categories\` DROP COLUMN \`key\``);
        await queryRunner.query(`ALTER TABLE \`app_users\` DROP COLUMN \`id\``);
        await queryRunner.query(`ALTER TABLE \`categories\` ADD \`data\` longtext COLLATE "utf8mb4_bin" NULL`);
        await queryRunner.query(`ALTER TABLE \`categories\` ADD \`mongo_id\` varchar(24) COLLATE "utf8mb4_general_ci" NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`transcripts\` ADD \`mongo_id\` varchar(24) NULL`);
        await queryRunner.query(`DROP INDEX \`IDX_ec2857bc1e1718797135dc71d7\` ON \`llm_instances\``);
        await queryRunner.query(`DROP INDEX \`IDX_ec2857bc1e1718797135dc71d7\` ON \`llm_instances\``);
        await queryRunner.query(`DROP TABLE \`llm_instances\``);
        await queryRunner.query(`CREATE UNIQUE INDEX \`ux_mongo_id\` ON \`categories\` (\`mongo_id\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`ux_transcripts_mongo_id\` ON \`transcripts\` (\`mongo_id\`)`);
    }

}
