import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialSchema1764775119125 implements MigrationInterface {
    name = 'InitialSchema1764775119125'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TYPE "public"."user_rights_role_enum" AS ENUM('terminal', 'guest', 'regular', 'manager', 'admin')`);
        await queryRunner.query(`CREATE TYPE "public"."user_rights_status_enum" AS ENUM('active', 'suspended', 'revoked')`);
        await queryRunner.query(`CREATE TABLE "user_rights" ("user_id" uuid NOT NULL, "role" "public"."user_rights_role_enum" NOT NULL DEFAULT 'regular', "status" "public"."user_rights_status_enum" NOT NULL DEFAULT 'active', "expires_at" TIMESTAMP, "permissions_json" json, "can_use_speech_input" boolean NOT NULL DEFAULT true, "can_view_own_inputs" boolean NOT NULL DEFAULT true, "can_view_all_inputs" boolean NOT NULL DEFAULT false, "can_delete_inputs" boolean NOT NULL DEFAULT false, "can_manage_terminals" boolean NOT NULL DEFAULT false, "can_manage_users" boolean NOT NULL DEFAULT false, "metadata" json, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "pk_user_rights" PRIMARY KEY ("user_id"))`);
        await queryRunner.query(`CREATE INDEX "ix_user_rights__status" ON "user_rights" ("status") `);
        await queryRunner.query(`CREATE INDEX "ix_user_rights__role" ON "user_rights" ("role") `);
        await queryRunner.query(`CREATE TABLE "users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "username" character varying(100) NOT NULL, "email" character varying(255) NOT NULL, "password_hash" character varying(255) NOT NULL, "profile_data" json, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "uq_users__username" UNIQUE ("username"), CONSTRAINT "uq_users__email" UNIQUE ("email"), CONSTRAINT "pk_users" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "ix_users__created_at" ON "users" ("created_at") `);
        await queryRunner.query(`CREATE INDEX "ix_users__email" ON "users" ("email") `);
        await queryRunner.query(`CREATE INDEX "ix_users__username" ON "users" ("username") `);
        await queryRunner.query(`CREATE TABLE "user_allowed_terminals" ("user_id" uuid NOT NULL, "terminal_id" uuid NOT NULL, "granted_at" TIMESTAMP NOT NULL DEFAULT now(), "expires_at" TIMESTAMP, "metadata" json, CONSTRAINT "pk_user_allowed_terminals" PRIMARY KEY ("user_id", "terminal_id"))`);
        await queryRunner.query(`CREATE TYPE "public"."appterminals_type_enum" AS ENUM('other', 'smart-tv', 'kiosk', 'tablet', 'mobile', 'browser')`);
        await queryRunner.query(`CREATE TYPE "public"."appterminals_status_enum" AS ENUM('active', 'inactive', 'maintenance')`);
        await queryRunner.query(`CREATE TABLE "appterminals" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "terminal_id" character varying(255) NOT NULL, "name" character varying(255) NOT NULL, "description" text, "type" "public"."app_terminals_type_enum" NOT NULL DEFAULT 'browser', "location" text, "capabilities_json" json, "status" "public"."app_terminals_status_enum" NOT NULL DEFAULT 'active', "last_active_at" TIMESTAMP, "assigned_user_id" uuid, "allowed_actions_json" json, "settings_json" json, "metadata_json" json, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "uq_app_terminals__terminal_id" UNIQUE ("terminal_id"), CONSTRAINT "pk_appterminals" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "ix_app_terminals__last_active_at" ON "appterminals" ("last_active_at") `);
        await queryRunner.query(`CREATE INDEX "ix_app_terminals__status" ON "appterminals" ("status") `);
        await queryRunner.query(`CREATE INDEX "ix_app_terminals__terminal_id" ON "appterminals" ("terminal_id") `);
        await queryRunner.query(`CREATE TYPE "public"."terminal_rights_status_enum" AS ENUM('active', 'suspended', 'maintenance')`);
        await queryRunner.query(`CREATE TABLE "terminal_rights" ("terminal_id" uuid NOT NULL, "role_key" character varying(100), "status" "public"."terminal_rights_status_enum" NOT NULL DEFAULT 'active', "allowed_actions_json" json, "restrictions_json" json, "metadata_json" json, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "pk_terminal_rights" PRIMARY KEY ("terminal_id"))`);
        await queryRunner.query(`CREATE INDEX "ix_terminal_rights__role_key" ON "terminal_rights" ("role_key") `);
        await queryRunner.query(`CREATE INDEX "ix_terminal_rights__status" ON "terminal_rights" ("status") `);
        await queryRunner.query(`CREATE TABLE "speech_test_inputs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid, "text" text NOT NULL, "expected_intent" character varying(255), "actual_intent" character varying(255), "passed" boolean NOT NULL DEFAULT false, "metadata" json, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "pk_speech_test_inputs" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "ix_speech_test_inputs__user_id" ON "speech_test_inputs" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "ix_speech_test_inputs__created_at" ON "speech_test_inputs" ("created_at") `);
        await queryRunner.query(`CREATE TABLE "speech_human_inputs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid, "terminal_id" uuid, "text" text NOT NULL, "language" character varying(10), "confidence" double precision, "metadata" json, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "pk_speech_human_inputs" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "ix_speech_human_inputs__terminal_id" ON "speech_human_inputs" ("terminal_id") `);
        await queryRunner.query(`CREATE INDEX "ix_speech_human_inputs__user_id" ON "speech_human_inputs" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "ix_speech_human_inputs__created_at" ON "speech_human_inputs" ("created_at") `);
        await queryRunner.query(`CREATE TABLE "categories" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "key" character varying(100) NOT NULL, "label" character varying(255) NOT NULL, "description" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "uq_categories__key" UNIQUE ("key"), CONSTRAINT "pk_categories" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "intent_logs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "timestamp" TIMESTAMP NOT NULL, "transcript" text NOT NULL, "intent_key" character varying(255) NOT NULL, "summary" text, "keywords_json" json, "confidence" double precision, "terminal_id" uuid, "category_id" uuid, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "pk_intent_logs" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "ix_intent_logs__terminal_id" ON "intent_logs" ("terminal_id") `);
        await queryRunner.query(`CREATE INDEX "ix_intent_logs__category_id" ON "intent_logs" ("category_id") `);
        await queryRunner.query(`CREATE INDEX "ix_intent_logs__timestamp" ON "intent_logs" ("timestamp") `);
        await queryRunner.query(`CREATE TABLE "speech_transcripts" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid, "terminal_id" uuid, "category_id" uuid, "transcript" text NOT NULL, "recognized_intent" text, "confidence" double precision, "assigned_area_id" character varying(255), "assigned_entity_id" character varying(255), "metadata" json, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "pk_speech_transcripts" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "ix_speech_transcripts__assigned_entity_id" ON "speech_transcripts" ("assigned_entity_id") `);
        await queryRunner.query(`CREATE INDEX "ix_speech_transcripts__assigned_area_id" ON "speech_transcripts" ("assigned_area_id") `);
        await queryRunner.query(`CREATE INDEX "ix_speech_transcripts__category_id" ON "speech_transcripts" ("category_id") `);
        await queryRunner.query(`CREATE INDEX "ix_speech_transcripts__terminal_id" ON "speech_transcripts" ("terminal_id") `);
        await queryRunner.query(`CREATE INDEX "ix_speech_transcripts__user_id" ON "speech_transcripts" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "ix_speech_transcripts__created_at" ON "speech_transcripts" ("created_at") `);
        await queryRunner.query(`CREATE TYPE "public"."event_logs_type_enum" AS ENUM('websocket', 'action', 'error', 'info', 'debug')`);
        await queryRunner.query(`CREATE TABLE "event_logs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "timestamp" TIMESTAMP NOT NULL, "type" "public"."event_logs_type_enum" NOT NULL DEFAULT 'info', "message" text NOT NULL, "user_id" uuid, "details" json, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "pk_event_logs" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "ix_event_logs__user_id" ON "event_logs" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "ix_event_logs__type" ON "event_logs" ("type") `);
        await queryRunner.query(`CREATE INDEX "ix_event_logs__timestamp" ON "event_logs" ("timestamp") `);
        await queryRunner.query(`CREATE TYPE "public"."ha_snapshots_status_enum" AS ENUM('completed', 'processing', 'pending', 'failed')`);
        await queryRunner.query(`CREATE TABLE "ha_snapshots" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "timestamp" TIMESTAMP NOT NULL, "ha_version" character varying(100), "import_date" TIMESTAMP NOT NULL, "status" "public"."ha_snapshots_status_enum" NOT NULL DEFAULT 'pending', "error_log" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "pk_ha_snapshots" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "ix_ha_snapshots__status" ON "ha_snapshots" ("status") `);
        await queryRunner.query(`CREATE INDEX "ix_ha_snapshots__import_date" ON "ha_snapshots" ("import_date") `);
        await queryRunner.query(`CREATE INDEX "ix_ha_snapshots__timestamp" ON "ha_snapshots" ("timestamp") `);
        await queryRunner.query(`CREATE TABLE "ha_persons" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "person_id" character varying(255) NOT NULL, "name" character varying(255) NOT NULL, "user_id" uuid, "picture" character varying(500), "device_trackers" json, "metadata" json, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_70e262fa8c63f11b4a8b681e977" UNIQUE ("person_id"), CONSTRAINT "PK_5f341b73e0de892739c128c5b18" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "ix_ha_persons__user_id" ON "ha_persons" ("user_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "uq_ha_persons__person_id" ON "ha_persons" ("person_id") `);
        await queryRunner.query(`CREATE TABLE "ha_areas" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "area_id" character varying(255) NOT NULL, "name" character varying(255) NOT NULL, "aliases" json, "floor" character varying(100), "icon" character varying(100), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_19c14e3df6906646d0c619e5159" UNIQUE ("area_id"), CONSTRAINT "PK_209177f91feac18ef3e69f42bcf" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "ix_ha_areas__name" ON "ha_areas" ("name") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "uq_ha_areas__area_id" ON "ha_areas" ("area_id") `);
        await queryRunner.query(`CREATE TABLE "ha_devices" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "device_id" character varying(255) NOT NULL, "name" character varying(255) NOT NULL, "manufacturer" character varying(255), "model" character varying(255), "sw_version" character varying(100), "configuration_url" character varying(500), "connections" json, "identifiers" json, "via_device_id" character varying(255), "area_id" character varying(255), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_103a4aac2364da92fe69c579b34" UNIQUE ("device_id"), CONSTRAINT "PK_ac30884d105c75520b71de9beb3" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "ix_ha_devices__area_id" ON "ha_devices" ("area_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "uq_ha_devices__device_id" ON "ha_devices" ("device_id") `);
        await queryRunner.query(`CREATE TYPE "public"."ha_entities_domain_enum" AS ENUM('light', 'switch', 'sensor', 'binary_sensor', 'climate', 'media_player', 'cover', 'fan', 'camera', 'lock', 'alarm_control_panel', 'automation', 'person', 'zone', 'other')`);
        await queryRunner.query(`CREATE TABLE "ha_entities" ("entity_id" character varying(255) NOT NULL, "domain" "public"."ha_entities_domain_enum" NOT NULL, "object_id" character varying(255) NOT NULL, "friendly_name" character varying(255) NOT NULL, "aliases" json, "icon" character varying(100), "device_class" character varying(100), "unit_of_measurement" character varying(100), "area_id" character varying(255), "device_id" character varying(255), "platform" character varying(255), "disabled" boolean NOT NULL DEFAULT false, "hidden" boolean NOT NULL DEFAULT false, "entity_category" character varying(100), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_1ea0706eb5defaadb39b56895dd" PRIMARY KEY ("entity_id"))`);
        await queryRunner.query(`CREATE INDEX "ix_ha_entities__device_id" ON "ha_entities" ("device_id") `);
        await queryRunner.query(`CREATE INDEX "ix_ha_entities__area_id" ON "ha_entities" ("area_id") `);
        await queryRunner.query(`CREATE INDEX "ix_ha_entities__domain" ON "ha_entities" ("domain") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "uq_ha_entities__entity_id" ON "ha_entities" ("entity_id") `);
        await queryRunner.query(`CREATE TABLE "ha_entity_states" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "entity_id" character varying(255) NOT NULL, "state" text NOT NULL, "timestamp" TIMESTAMP NOT NULL, "snapshot_id" uuid, "last_changed" TIMESTAMP, "last_updated" TIMESTAMP, CONSTRAINT "PK_72851f6e2f2c465c3222dedd61d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "ix_ha_entity_states__entity_timestamp" ON "ha_entity_states" ("entity_id", "timestamp") `);
        await queryRunner.query(`CREATE INDEX "ix_ha_entity_states__snapshot_id" ON "ha_entity_states" ("snapshot_id") `);
        await queryRunner.query(`CREATE INDEX "ix_ha_entity_states__timestamp" ON "ha_entity_states" ("timestamp") `);
        await queryRunner.query(`CREATE INDEX "ix_ha_entity_states__entity_id" ON "ha_entity_states" ("entity_id") `);
        await queryRunner.query(`CREATE TABLE "ha_entity_attributes" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "entity_id" character varying(255) NOT NULL, "attribute_key" character varying(255) NOT NULL, "attribute_value" json NOT NULL, "value_type" character varying(50), CONSTRAINT "pk_ha_entity_attributes" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "ix_ha_entity_attributes__entity_key" ON "ha_entity_attributes" ("entity_id", "attribute_key") `);
        await queryRunner.query(`CREATE INDEX "ix_ha_entity_attributes__attribute_key" ON "ha_entity_attributes" ("attribute_key") `);
        await queryRunner.query(`CREATE INDEX "ix_ha_entity_attributes__entity_id" ON "ha_entity_attributes" ("entity_id") `);
        await queryRunner.query(`ALTER TABLE "user_rights" ADD CONSTRAINT "fk_user_rights__users__user_id" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "user_allowed_terminals" ADD CONSTRAINT "fk_user_allowed_terminals__users__user_id" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "user_allowed_terminals" ADD CONSTRAINT "fk_user_allowed_terminals__app_terminals__terminal_id" FOREIGN KEY ("terminal_id") REFERENCES "app_terminals"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "app_terminals" ADD CONSTRAINT "fk_app_terminals__users__assigned_user_id" FOREIGN KEY ("assigned_user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "terminal_rights" ADD CONSTRAINT "fk_terminal_rights__app_terminals__terminal_id" FOREIGN KEY ("terminal_id") REFERENCES "app_terminals"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "speech_test_inputs" ADD CONSTRAINT "fk_speech_test_inputs__users__user_id" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "speech_human_inputs" ADD CONSTRAINT "fk_speech_human_inputs__users__user_id" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "speech_human_inputs" ADD CONSTRAINT "fk_speech_human_inputs__app_terminals__terminal_id" FOREIGN KEY ("terminal_id") REFERENCES "app_terminals"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "intent_logs" ADD CONSTRAINT "fk_intent_logs__categories__category_id" FOREIGN KEY ("category_id") REFERENCES "categories"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "intent_logs" ADD CONSTRAINT "fk_intent_logs__app_terminals__terminal_id" FOREIGN KEY ("terminal_id") REFERENCES "app_terminals"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "speech_transcripts" ADD CONSTRAINT "fk_speech_transcripts__users__user_id" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "speech_transcripts" ADD CONSTRAINT "fk_speech_transcripts__app_terminals__terminal_id" FOREIGN KEY ("terminal_id") REFERENCES "app_terminals"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "speech_transcripts" ADD CONSTRAINT "fk_speech_transcripts__categories__category_id" FOREIGN KEY ("category_id") REFERENCES "categories"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "event_logs" ADD CONSTRAINT "fk_event_logs__users__user_id" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ha_persons" ADD CONSTRAINT "fk_ha_persons__users__user_id" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ha_devices" ADD CONSTRAINT "fk_ha_devices__ha_areas__area_id" FOREIGN KEY ("area_id") REFERENCES "ha_areas"("area_id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ha_devices" ADD CONSTRAINT "fk_ha_devices__ha_devices__via_device_id" FOREIGN KEY ("via_device_id") REFERENCES "ha_devices"("device_id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ha_entities" ADD CONSTRAINT "fk_ha_entities__ha_areas__area_id" FOREIGN KEY ("area_id") REFERENCES "ha_areas"("area_id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ha_entities" ADD CONSTRAINT "fk_ha_entities__ha_devices__device_id" FOREIGN KEY ("device_id") REFERENCES "ha_devices"("device_id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ha_entity_states" ADD CONSTRAINT "fk_ha_entity_states__ha_entities__entity_id" FOREIGN KEY ("entity_id") REFERENCES "ha_entities"("entity_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ha_entity_states" ADD CONSTRAINT "fk_ha_entity_states__ha_snapshots__snapshot_id" FOREIGN KEY ("snapshot_id") REFERENCES "ha_snapshots"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "ha_entity_attributes" ADD CONSTRAINT "fk_ha_entity_attributes__ha_entities__entity_id" FOREIGN KEY ("entity_id") REFERENCES "ha_entities"("entity_id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "ha_entity_attributes" DROP CONSTRAINT "fk_ha_entity_attributes__ha_entities__entity_id"`);
        await queryRunner.query(`ALTER TABLE "ha_entity_states" DROP CONSTRAINT "fk_ha_entity_states__ha_snapshots__snapshot_id"`);
        await queryRunner.query(`ALTER TABLE "ha_entity_states" DROP CONSTRAINT "fk_ha_entity_states__ha_entities__entity_id"`);
        await queryRunner.query(`ALTER TABLE "ha_entities" DROP CONSTRAINT "fk_ha_entities__ha_devices__device_id"`);
        await queryRunner.query(`ALTER TABLE "ha_entities" DROP CONSTRAINT "fk_ha_entities__ha_areas__area_id"`);
        await queryRunner.query(`ALTER TABLE "ha_devices" DROP CONSTRAINT "fk_ha_devices__ha_devices__via_device_id"`);
        await queryRunner.query(`ALTER TABLE "ha_devices" DROP CONSTRAINT "fk_ha_devices__ha_areas__area_id"`);
        await queryRunner.query(`ALTER TABLE "ha_persons" DROP CONSTRAINT "fk_ha_persons__users__user_id"`);
        await queryRunner.query(`ALTER TABLE "event_logs" DROP CONSTRAINT "fk_event_logs__users__user_id"`);
        await queryRunner.query(`ALTER TABLE "speech_transcripts" DROP CONSTRAINT "fk_speech_transcripts__categories__category_id"`);
        await queryRunner.query(`ALTER TABLE "speech_transcripts" DROP CONSTRAINT "fk_speech_transcripts__app_terminals__terminal_id"`);
        await queryRunner.query(`ALTER TABLE "speech_transcripts" DROP CONSTRAINT "fk_speech_transcripts__users__user_id"`);
        await queryRunner.query(`ALTER TABLE "intent_logs" DROP CONSTRAINT "fk_intent_logs__app_terminals__terminal_id"`);
        await queryRunner.query(`ALTER TABLE "intent_logs" DROP CONSTRAINT "fk_intent_logs__categories__category_id"`);
        await queryRunner.query(`ALTER TABLE "speech_human_inputs" DROP CONSTRAINT "fk_speech_human_inputs__app_terminals__terminal_id"`);
        await queryRunner.query(`ALTER TABLE "speech_human_inputs" DROP CONSTRAINT "fk_speech_human_inputs__users__user_id"`);
        await queryRunner.query(`ALTER TABLE "speech_test_inputs" DROP CONSTRAINT "fk_speech_test_inputs__users__user_id"`);
        await queryRunner.query(`ALTER TABLE "terminal_rights" DROP CONSTRAINT "fk_terminal_rights__app_terminals__terminal_id"`);
        await queryRunner.query(`ALTER TABLE "app_terminals" DROP CONSTRAINT "fk_app_terminals__users__assigned_user_id"`);
        await queryRunner.query(`ALTER TABLE "user_allowed_terminals" DROP CONSTRAINT "fk_user_allowed_terminals__app_terminals__terminal_id"`);
        await queryRunner.query(`ALTER TABLE "user_allowed_terminals" DROP CONSTRAINT "fk_user_allowed_terminals__users__user_id"`);
        await queryRunner.query(`ALTER TABLE "user_rights" DROP CONSTRAINT "fk_user_rights__users__user_id"`);
        await queryRunner.query(`DROP INDEX "public"."ix_ha_entity_attributes__entity_id"`);
        await queryRunner.query(`DROP INDEX "public"."ix_ha_entity_attributes__attribute_key"`);
        await queryRunner.query(`DROP INDEX "public"."ix_ha_entity_attributes__entity_key"`);
        await queryRunner.query(`DROP TABLE "ha_entity_attributes"`);
        await queryRunner.query(`DROP INDEX "public"."ix_ha_entity_states__entity_id"`);
        await queryRunner.query(`DROP INDEX "public"."ix_ha_entity_states__timestamp"`);
        await queryRunner.query(`DROP INDEX "public"."ix_ha_entity_states__snapshot_id"`);
        await queryRunner.query(`DROP INDEX "public"."ix_ha_entity_states__entity_timestamp"`);
        await queryRunner.query(`DROP TABLE "ha_entity_states"`);
        await queryRunner.query(`DROP INDEX "public"."uq_ha_entities__entity_id"`);
        await queryRunner.query(`DROP INDEX "public"."ix_ha_entities__domain"`);
        await queryRunner.query(`DROP INDEX "public"."ix_ha_entities__area_id"`);
        await queryRunner.query(`DROP INDEX "public"."ix_ha_entities__device_id"`);
        await queryRunner.query(`DROP TABLE "ha_entities"`);
        await queryRunner.query(`DROP TYPE "public"."ha_entities_domain_enum"`);
        await queryRunner.query(`DROP INDEX "public"."uq_ha_devices__device_id"`);
        await queryRunner.query(`DROP INDEX "public"."ix_ha_devices__area_id"`);
        await queryRunner.query(`DROP TABLE "ha_devices"`);
        await queryRunner.query(`DROP INDEX "public"."uq_ha_areas__area_id"`);
        await queryRunner.query(`DROP INDEX "public"."ix_ha_areas__name"`);
        await queryRunner.query(`DROP TABLE "ha_areas"`);
        await queryRunner.query(`DROP INDEX "public"."uq_ha_persons__person_id"`);
        await queryRunner.query(`DROP INDEX "public"."ix_ha_persons__user_id"`);
        await queryRunner.query(`DROP TABLE "ha_persons"`);
        await queryRunner.query(`DROP INDEX "public"."ix_ha_snapshots__timestamp"`);
        await queryRunner.query(`DROP INDEX "public"."ix_ha_snapshots__import_date"`);
        await queryRunner.query(`DROP INDEX "public"."ix_ha_snapshots__status"`);
        await queryRunner.query(`DROP TABLE "ha_snapshots"`);
        await queryRunner.query(`DROP TYPE "public"."ha_snapshots_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."ix_event_logs__timestamp"`);
        await queryRunner.query(`DROP INDEX "public"."ix_event_logs__type"`);
        await queryRunner.query(`DROP INDEX "public"."ix_event_logs__user_id"`);
        await queryRunner.query(`DROP TABLE "event_logs"`);
        await queryRunner.query(`DROP TYPE "public"."event_logs_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."ix_speech_transcripts__created_at"`);
        await queryRunner.query(`DROP INDEX "public"."ix_speech_transcripts__user_id"`);
        await queryRunner.query(`DROP INDEX "public"."ix_speech_transcripts__terminal_id"`);
        await queryRunner.query(`DROP INDEX "public"."ix_speech_transcripts__category_id"`);
        await queryRunner.query(`DROP INDEX "public"."ix_speech_transcripts__assigned_area_id"`);
        await queryRunner.query(`DROP INDEX "public"."ix_speech_transcripts__assigned_entity_id"`);
        await queryRunner.query(`DROP TABLE "speech_transcripts"`);
        await queryRunner.query(`DROP INDEX "public"."ix_intent_logs__timestamp"`);
        await queryRunner.query(`DROP INDEX "public"."ix_intent_logs__category_id"`);
        await queryRunner.query(`DROP INDEX "public"."ix_intent_logs__terminal_id"`);
        await queryRunner.query(`DROP TABLE "intent_logs"`);
        await queryRunner.query(`DROP TABLE "categories"`);
        await queryRunner.query(`DROP INDEX "public"."ix_speech_human_inputs__created_at"`);
        await queryRunner.query(`DROP INDEX "public"."ix_speech_human_inputs__user_id"`);
        await queryRunner.query(`DROP INDEX "public"."ix_speech_human_inputs__terminal_id"`);
        await queryRunner.query(`DROP TABLE "speech_human_inputs"`);
        await queryRunner.query(`DROP INDEX "public"."ix_speech_test_inputs__created_at"`);
        await queryRunner.query(`DROP INDEX "public"."ix_speech_test_inputs__user_id"`);
        await queryRunner.query(`DROP TABLE "speech_test_inputs"`);
        await queryRunner.query(`DROP INDEX "public"."ix_terminal_rights__status"`);
        await queryRunner.query(`DROP INDEX "public"."ix_terminal_rights__role_key"`);
        await queryRunner.query(`DROP TABLE "terminal_rights"`);
        await queryRunner.query(`DROP TYPE "public"."terminal_rights_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."ix_app_terminals__terminal_id"`);
        await queryRunner.query(`DROP INDEX "public"."ix_app_terminals__status"`);
        await queryRunner.query(`DROP INDEX "public"."ix_app_terminals__last_active_at"`);
        await queryRunner.query(`DROP TABLE "app_terminals"`);
        await queryRunner.query(`DROP TYPE "public"."app_terminals_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."app_terminals_type_enum"`);
        await queryRunner.query(`DROP TABLE "user_allowed_terminals"`);
        await queryRunner.query(`DROP INDEX "public"."ix_users__username"`);
        await queryRunner.query(`DROP INDEX "public"."ix_users__email"`);
        await queryRunner.query(`DROP INDEX "public"."ix_users__created_at"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP INDEX "public"."ix_user_rights__role"`);
        await queryRunner.query(`DROP INDEX "public"."ix_user_rights__status"`);
        await queryRunner.query(`DROP TABLE "user_rights"`);
        await queryRunner.query(`DROP TYPE "public"."user_rights_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."user_rights_role_enum"`);
    }

}
